
name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ecommerce_app_test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Set up database
      env:
        RAILS_ENV: test
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rails db:create
        bundle exec rails db:schema:load

    - name: Run tests
      run: |
        RAILS_ENV=test bundle exec rails test
        
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git reset --hard
        git config --global user.email "wongwf82@gmail.com"
        git config --global user.name "Fai Wong"
        git config pull.rebase true
        git config rebase.autoSquash true
        git config rebase.instructionFormat '%an <%ae> %s'
        git pull --rebase --strategy-option=theirs https://heroku:$HEROKU_API_KEY@git.heroku.com/my-ecommerce-app.git main
        git pull --rebase https://heroku:$HEROKU_API_KEY@git.heroku.com/my-ecommerce-app.git main
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/my-ecommerce-app.git main